version: "3.9"

services:
  app:
    image: hurima-frontend
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ~/.aws:/home/node/.aws
    ports:
      - 3000:3000
