server:
  port: 8181
  compression:
    enabled: true

spring:
  datasource:
    name: hurimadb
    url: jdbc:postgresql://localhost:5432/hurimadb?allowPublicKeyRetrieval=true
    username: postgres
    password: password

    hikari:
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: ConnPool

  jpa:
    show-sql: true  #
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/migration

  jmx:
    enabled: true

## App Properties
app:
  jwtExpirationInMs: 604800000
  jwtSecret: "9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f"

management:
  endpoints:
    web:
      exposure:
        include: restart,health
  endpoint:
    restart:
      enabled: true



