server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true

spring:
  application:
    name: hurima-api-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  mail:
    host: smtp.gmail.com
    username: hurima.dev@gmail.com
    protocol: smtps
    port: 465
    password: nphtrhjbiuvmrlnl
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          starttls:
            required: true
            enable: true
          auth: false

  datasource:
    name: hurimadb
    url: jdbc:postgresql://localhost:5432/hurimadb?useSSL=false
    username: postgres
    password: password

    hikari:
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: ConnPool

  jpa:
    show-sql: true  #
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: false
    table: schema_history

  jmx:
    enabled: true

  servlet:
    multipart:
      enabled: true

  thymeleaf:
    enabled: true
    encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: restart,health
  endpoint:
    restart:
      enabled: true

######## App Properties ########

app:
  mail:
    debug: true
  jwtHeader: Authorization
  jwtExpirationInMs: 604800000
  jwtSecretKey: "9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f"

hostname: localhost:3000


